Dropdown
migoJerry101/wms-app pull request #11
Opened 2023-07-24 06:37 UTC by jsandiegosnrshopping01

2023-07-24 06:48 UTC, migoJerry101 requested changes

2023-07-24 06:48 UTC, migoJerry101 commented on src/Components/Dropdown.tsx
> +    const menuItemTest = () =>{
remove test in variable name

2023-07-24 06:48 UTC, migoJerry101 commented on src/Components/Dropdown.tsx
> +    <FormControl fullWidth>
make width dynamic for reusability

2023-07-24 07:26 UTC, ralcaraz22 approved these changes

2023-07-25 02:16 UTC, migoJerry101 approved these changes

2023-07-25 02:18 UTC, merged